<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Type' => 'Тип',
    'Section' => 'Розділ',
    'Key' => 'Ключ',
    'Value' => 'Значення',
    'Status' => 'Стан',
    'Description' => 'Опис',
    'Created Date' => 'Дата Створення',
    'Updated Date' => 'Дата Поновлення',
    'Settings' => 'Налаштування',
    'Create Setting' => 'Створити Налаштування',
    'Select Type' => 'Оберіть Тип',
    'Select Section' => 'Оберіть Розділ',
    'Select Status' => 'Оберіть Стан',
    'Actions' => 'Дії',
    'Active' => 'Активно',
    'Inactive' => 'Не активно',
    'Translate' => 'Переклад',
    'Translated' => 'Перекладено',
    'Not translated' => 'Не перекладено',
    'Update Setting: {0} -> {1}' => 'Редагування Налаштування: {0} -> {1}',
    'Update Setting' => 'Редагування Налаштування',
    'Update' => 'Редагувати',
    'Create' => 'Створити',
    'Delete' => 'Видалити',
    'Go Back' => 'Повернутися',
    'String' => 'Строка',
    'Integer' => 'Ціле число',
    'Boolean' => '0 або 1',
    'Float' => 'Число з плаваючою комою',
    'Null' => 'Null',
    'Setting has been created.' => 'Налаштування було створено.',
    'Setting has been updated.' => 'Налаштування було оновлено.',
    'Setting has been deleted.' => 'Налаштування було видалено.',
    'The requested page does not exist.' => 'Помилка 404 - сторінка не знайдена!',
    'If the value does not require translation, you can leave the field empty' => 'Якщо значення не потребує перекладу, ви можете залишити поле порожнім',
];
